package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTAssignmentDeclarator.java */

public class ASTAssignmentDeclarator extends SimpleNode {
  public ASTAssignmentDeclarator(int id) {
    super(id);
  }

  public ASTAssignmentDeclarator(Nassau p, int id) {
    super(p, id);
  }

}
