package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java */

public class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Nassau p, int id) {
    super(p, id);
  }

}
