package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTArrayType.java */

public class ASTArrayType extends SimpleNode {
  public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(Nassau p, int id) {
    super(p, id);
  }

}
