package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTAssignmentOperator.java */

public class ASTAssignmentOperator extends SimpleNode {
    private Object value;
  public ASTAssignmentOperator(int id) {
    super(id);
  }

  public ASTAssignmentOperator(Nassau p, int id) {
    super(p, id);
  }
  
  public void jjtSetValue(Object v){value = v;}
  public Object jjtGetValue(){return value;}

}
