package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTAssignment.java */

public class ASTAssignment extends SimpleNode {
  public ASTAssignment(int id) {
    super(id);
  }

  public ASTAssignment(Nassau p, int id) {
    super(p, id);
  }

}
