package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTArrayDimension.java */

public class ASTArrayDimension extends SimpleNode {
  public ASTArrayDimension(int id) {
    super(id);
  }

  public ASTArrayDimension(Nassau p, int id) {
    super(p, id);
  }

}
