package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTArrayDeclarator.java */

public class ASTArrayDeclarator extends SimpleNode {
  public ASTArrayDeclarator(int id) {
    super(id);
  }

  public ASTArrayDeclarator(Nassau p, int id) {
    super(p, id);
  }

}
