package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTArrayPrimarySuffix.java */

public class ASTArrayPrimarySuffix extends SimpleNode {
  public ASTArrayPrimarySuffix(int id) {
    super(id);
  }

  public ASTArrayPrimarySuffix(Nassau p, int id) {
    super(p, id);
  }

}
