package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTBreakStatement.java */

public class ASTBreakStatement extends SimpleNode {
  public ASTBreakStatement(int id) {
    super(id);
  }

  public ASTBreakStatement(Nassau p, int id) {
    super(p, id);
  }

}
