package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTBiggerRelationalExpression.java */

public class ASTBiggerRelationalExpression extends SimpleNode {
  public ASTBiggerRelationalExpression(int id) {
    super(id);
  }

  public ASTBiggerRelationalExpression(Nassau p, int id) {
    super(p, id);
  }

}
