package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTBiggerEqRelationalExpression.java */

public class ASTBiggerEqRelationalExpression extends SimpleNode {
  public ASTBiggerEqRelationalExpression(int id) {
    super(id);
  }

  public ASTBiggerEqRelationalExpression(Nassau p, int id) {
    super(p, id);
  }

}
