package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTConstructorDeclaration.java */

public class ASTConstructorDeclaration extends SimpleNode {
  public ASTConstructorDeclaration(int id) {
    super(id);
  }

  public ASTConstructorDeclaration(Nassau p, int id) {
    super(p, id);
  }

}
