package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java */

public class ASTContinueStatement extends SimpleNode {
  public ASTContinueStatement(int id) {
    super(id);
  }

  public ASTContinueStatement(Nassau p, int id) {
    super(p, id);
  }

}
