package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTConditonalOrExpression.java */

public class ASTConditonalOrExpression extends SimpleNode {
  public ASTConditonalOrExpression(int id) {
    super(id);
  }

  public ASTConditonalOrExpression(Nassau p, int id) {
    super(p, id);
  }

}
