package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTCharacterLiteral.java */

public class ASTCharacterLiteral extends SimpleNode {
  public ASTCharacterLiteral(int id) {
    super(id);
  }

  public ASTCharacterLiteral(Nassau p, int id) {
    super(p, id);
  }

}
