package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTClassInstanceCreationExpression.java */

public class ASTClassInstanceCreationExpression extends SimpleNode {
  public ASTClassInstanceCreationExpression(int id) {
    super(id);
  }

  public ASTClassInstanceCreationExpression(Nassau p, int id) {
    super(p, id);
  }

}
