package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTConstructorImplement.java */

public class ASTConstructorImplement extends SimpleNode {
  public ASTConstructorImplement(int id) {
    super(id);
  }

  public ASTConstructorImplement(Nassau p, int id) {
    super(p, id);
  }

}
