package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTClassImplement.java */

public class ASTClassImplement extends SimpleNode {
  public ASTClassImplement(int id) {
    super(id);
  }

  public ASTClassImplement(Nassau p, int id) {
    super(p, id);
  }

}
