package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTClassMethodImplement.java */

public class ASTClassMethodImplement extends SimpleNode {
  public ASTClassMethodImplement(int id) {
    super(id);
  }

  public ASTClassMethodImplement(Nassau p, int id) {
    super(p, id);
  }

}
