package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTCallFuntion.java */

public class ASTCallFuntion extends SimpleNode {
  public ASTCallFuntion(int id) {
    super(id);
  }

  public ASTCallFuntion(Nassau p, int id) {
    super(p, id);
  }

}
