package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTDeleteStatement.java */

public class ASTDeleteStatement extends SimpleNode {
  public ASTDeleteStatement(int id) {
    super(id);
  }

  public ASTDeleteStatement(Nassau p, int id) {
    super(p, id);
  }

}
