package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTDivideMultiplicativeExpression.java */

public class ASTDivideMultiplicativeExpression extends SimpleNode {
  public ASTDivideMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTDivideMultiplicativeExpression(Nassau p, int id) {
    super(p, id);
  }

}
