package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java */

public class ASTDoStatement extends SimpleNode {
  public ASTDoStatement(int id) {
    super(id);
  }

  public ASTDoStatement(Nassau p, int id) {
    super(p, id);
  }

}
