package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTExpressionPrimaryPrefix.java */

public class ASTExpressionPrimaryPrefix extends SimpleNode {
  public ASTExpressionPrimaryPrefix(int id) {
    super(id);
  }

  public ASTExpressionPrimaryPrefix(Nassau p, int id) {
    super(p, id);
  }

}
