package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTElseBlock.java */

public class ASTElseBlock extends SimpleNode {
  public ASTElseBlock(int id) {
    super(id);
  }

  public ASTElseBlock(Nassau p, int id) {
    super(p, id);
  }

}
