package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTForStatement.java */

public class ASTForStatement extends SimpleNode {
  public ASTForStatement(int id) {
    super(id);
  }

  public ASTForStatement(Nassau p, int id) {
    super(p, id);
  }

}
