package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTFloatingPointLiteral.java */

public class ASTFloatingPointLiteral extends SimpleNode {
  public ASTFloatingPointLiteral(int id) {
    super(id);
  }

  public ASTFloatingPointLiteral(Nassau p, int id) {
    super(p, id);
  }

}
