package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTFullName.java */

public class ASTFullName extends SimpleNode {
  public ASTFullName(int id) {
    super(id);
  }

  public ASTFullName(Nassau p, int id) {
    super(p, id);
  }

}
