package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTFieldModifier.java */

public class ASTFieldModifier extends SimpleNode {
  public ASTFieldModifier(int id) {
    super(id);
  }

  public ASTFieldModifier(Nassau p, int id) {
    super(p, id);
  }

}
