package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTForInit.java */

public class ASTForInit extends SimpleNode {
  public ASTForInit(int id) {
    super(id);
  }

  public ASTForInit(Nassau p, int id) {
    super(p, id);
  }

}
