package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java */

public class ASTImportDeclaration extends SimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(Nassau p, int id) {
    super(p, id);
  }

}
