package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java */

public class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(Nassau p, int id) {
    super(p, id);
  }

}
