package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTIntegerLiteral.java */

public class ASTIntegerLiteral extends SimpleNode {
  public ASTIntegerLiteral(int id) {
    super(id);
  }

  public ASTIntegerLiteral(Nassau p, int id) {
    super(p, id);
  }

}
