package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */

public class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(Nassau p, int id) {
    super(p, id);
  }

}
