package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTLeftThreeShiftExpression.java */

public class ASTLeftThreeShiftExpression extends SimpleNode {
  public ASTLeftThreeShiftExpression(int id) {
    super(id);
  }

  public ASTLeftThreeShiftExpression(Nassau p, int id) {
    super(p, id);
  }

}
