package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclarationStatement.java */

public class ASTLocalVariableDeclarationStatement extends SimpleNode {
  public ASTLocalVariableDeclarationStatement(int id) {
    super(id);
  }

  public ASTLocalVariableDeclarationStatement(Nassau p, int id) {
    super(p, id);
  }

}
