package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTLessEqRelationalExpression.java */

public class ASTLessEqRelationalExpression extends SimpleNode {
  public ASTLessEqRelationalExpression(int id) {
    super(id);
  }

  public ASTLessEqRelationalExpression(Nassau p, int id) {
    super(p, id);
  }

}
