package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTLessRelationalExpression.java */

public class ASTLessRelationalExpression extends SimpleNode {
  public ASTLessRelationalExpression(int id) {
    super(id);
  }

  public ASTLessRelationalExpression(Nassau p, int id) {
    super(p, id);
  }

}
