package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTLeftShiftExpression.java */

public class ASTLeftShiftExpression extends SimpleNode {
  public ASTLeftShiftExpression(int id) {
    super(id);
  }

  public ASTLeftShiftExpression(Nassau p, int id) {
    super(p, id);
  }

}
