package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTMultipleMultiplicativeExpression.java */

public class ASTMultipleMultiplicativeExpression extends SimpleNode {
  public ASTMultipleMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTMultipleMultiplicativeExpression(Nassau p, int id) {
    super(p, id);
  }

}
