package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java */

public class ASTMethodDeclaration extends SimpleNode {
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(Nassau p, int id) {
    super(p, id);
  }

}
