package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTMethodModifier.java */

public class ASTMethodModifier extends SimpleNode {
  public ASTMethodModifier(int id) {
    super(id);
  }

  public ASTMethodModifier(Nassau p, int id) {
    super(p, id);
  }

}
