package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTMinusAdditiveExpression.java */

public class ASTMinusAdditiveExpression extends SimpleNode {
  public ASTMinusAdditiveExpression(int id) {
    super(id);
  }

  public ASTMinusAdditiveExpression(Nassau p, int id) {
    super(p, id);
  }

}
