package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTNotEqualityExpression.java */

public class ASTNotEqualityExpression extends SimpleNode {
  public ASTNotEqualityExpression(int id) {
    super(id);
  }

  public ASTNotEqualityExpression(Nassau p, int id) {
    super(p, id);
  }

}
