package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTNotExpression.java */

public class ASTNotExpression extends SimpleNode {
  public ASTNotExpression(int id) {
    super(id);
  }

  public ASTNotExpression(Nassau p, int id) {
    super(p, id);
  }

}
