/* Generated By:JJTree: Do not edit this line. ASTName.java */
package sjtu.ParseAnalyse;

public class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(Nassau p, int id) {
    super(p, id);
  }

}
