package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTOppositeExpression.java */

public class ASTOppositeExpression extends SimpleNode {
  public ASTOppositeExpression(int id) {
    super(id);
  }

  public ASTOppositeExpression(Nassau p, int id) {
    super(p, id);
  }

}
