package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTPostincrementExpression.java */

public class ASTPostincrementExpression extends SimpleNode {
  public ASTPostincrementExpression(int id) {
    super(id);
  }

  public ASTPostincrementExpression(Nassau p, int id) {
    super(p, id);
  }

}
