package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTPlusAdditiveExpression.java */

public class ASTPlusAdditiveExpression extends SimpleNode {
  public ASTPlusAdditiveExpression(int id) {
    super(id);
  }

  public ASTPlusAdditiveExpression(Nassau p, int id) {
    super(p, id);
  }

}
