package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTPreincrementExpression.java */

public class ASTPreincrementExpression extends SimpleNode {
  public ASTPreincrementExpression(int id) {
    super(id);
  }

  public ASTPreincrementExpression(Nassau p, int id) {
    super(p, id);
  }

}
