/* Generated By:JJTree: Do not edit this line. ASTPrintStatement.java */
package sjtu.ParseAnalyse;

public class ASTPrintStatement extends SimpleNode {
  public ASTPrintStatement(int id) {
    super(id);
  }

  public ASTPrintStatement(Nassau p, int id) {
    super(p, id);
  }

}
