package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTPredecrementExpression.java */

public class ASTPredecrementExpression extends SimpleNode {
  public ASTPredecrementExpression(int id) {
    super(id);
  }

  public ASTPredecrementExpression(Nassau p, int id) {
    super(p, id);
  }

}
