package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTPostdecrementExpression.java */

public class ASTPostdecrementExpression extends SimpleNode {
  public ASTPostdecrementExpression(int id) {
    super(id);
  }

  public ASTPostdecrementExpression(Nassau p, int id) {
    super(p, id);
  }

}
