package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTPackageDeclaration.java */

public class ASTPackageDeclaration extends SimpleNode {
  public ASTPackageDeclaration(int id) {
    super(id);
  }

  public ASTPackageDeclaration(Nassau p, int id) {
    super(p, id);
  }

}
