package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTRightShiftExpression.java */

public class ASTRightShiftExpression extends SimpleNode {
  public ASTRightShiftExpression(int id) {
    super(id);
  }

  public ASTRightShiftExpression(Nassau p, int id) {
    super(p, id);
  }

}
