package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTRemainMultiplicativeExpression.java */

public class ASTRemainMultiplicativeExpression extends SimpleNode {
  public ASTRemainMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTRemainMultiplicativeExpression(Nassau p, int id) {
    super(p, id);
  }

}
