package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTStringLiteral.java */

public class ASTStringLiteral extends SimpleNode {
  public ASTStringLiteral(int id) {
    super(id);
  }

  public ASTStringLiteral(Nassau p, int id) {
    super(p, id);
  }

}
