package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTStaticInitializer.java */

public class ASTStaticInitializer extends SimpleNode {
  public ASTStaticInitializer(int id) {
    super(id);
  }

  public ASTStaticInitializer(Nassau p, int id) {
    super(p, id);
  }

}
