package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTStart.java */

public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Nassau p, int id) {
    super(p, id);
  }

}
