package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTThisPrimaryPrefix.java */

public class ASTThisPrimaryPrefix extends SimpleNode {
  public ASTThisPrimaryPrefix(int id) {
    super(id);
  }

  public ASTThisPrimaryPrefix(Nassau p, int id) {
    super(p, id);
  }

}
