package sjtu.ParseAnalyse;

/* Generated By:JJTree: Do not edit this line. ASTvoidType.java */

public class ASTvoidType extends SimpleNode {
  public ASTvoidType(int id) {
    super(id);
  }

  public ASTvoidType(Nassau p, int id) {
    super(p, id);
  }

}
