package sjtu.ParseAnalyse;
/* Generated By:JJTree&JavaCC: Do not edit this line. NassauConstants.java */
public interface NassauConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int FORMAL_COMMENT = 8;
  int MULTI_LINE_COMMENT = 9;
  int BOOLEAN = 10;
  int BREAK = 11;
  int BYTE = 12;
  int CHAR = 13;
  int CLASS = 14;
  int CONTINUE = 15;
  int DO = 16;
  int DOUBLE = 17;
  int ELSE = 18;
  int ELIF = 19;
  int FALSE = 20;
  int FLOAT = 21;
  int FOR = 22;
  int IF = 23;
  int IMPLEMENT = 24;
  int IMPORT = 25;
  int INT = 26;
  int LONG = 27;
  int NEW = 28;
  int NULL = 29;
  int PACKAGE = 30;
  int PRIVATE = 31;
  int PRINT = 32;
  int PUBLIC = 33;
  int RETURN = 34;
  int SHORT = 35;
  int STATIC = 36;
  int THIS = 37;
  int TRUE = 38;
  int VOID = 39;
  int WHILE = 40;
  int INTEGER_LITERAL = 41;
  int DECIMAL_LITERAL = 42;
  int HEX_LITERAL = 43;
  int OCTAL_LITERAL = 44;
  int FLOATING_POINT_LITERAL = 45;
  int EXPONENT = 46;
  int CHARACTER_LITERAL = 47;
  int STRING_LITERAL = 48;
  int IDENTIFIER = 49;
  int LETTER = 50;
  int DIGIT = 51;
  int LPAREN = 52;
  int RPAREN = 53;
  int LBRACE = 54;
  int RBRACE = 55;
  int LBRACKET = 56;
  int RBRACKET = 57;
  int SEMICOLON = 58;
  int COMMA = 59;
  int DOT = 60;
  int ASSIGN = 61;
  int GT = 62;
  int LT = 63;
  int BANG = 64;
  int TILDE = 65;
  int HOOK = 66;
  int COLON = 67;
  int EQ = 68;
  int LE = 69;
  int GE = 70;
  int NE = 71;
  int SC_OR = 72;
  int SC_AND = 73;
  int INCR = 74;
  int DECR = 75;
  int PLUS = 76;
  int MINUS = 77;
  int STAR = 78;
  int SLASH = 79;
  int BIT_AND = 80;
  int BIT_OR = 81;
  int XOR = 82;
  int REM = 83;
  int LSHIFT = 84;
  int RSIGNEDSHIFT = 85;
  int RUNSIGNEDSHIFT = 86;
  int PLUSASSIGN = 87;
  int MINUSASSIGN = 88;
  int STARASSIGN = 89;
  int SLASHASSIGN = 90;
  int ANDASSIGN = 91;
  int ORASSIGN = 92;
  int XORASSIGN = 93;
  int REMASSIGN = 94;
  int LSHIFTASSIGN = 95;
  int RSIGNEDSHIFTASSIGN = 96;
  int RUNSIGNEDSHIFTASSIGN = 97;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"char\"",
    "\"class\"",
    "\"continue\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"elif\"",
    "\"false\"",
    "\"float\"",
    "\"for\"",
    "\"if\"",
    "\"implement\"",
    "\"import\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"print\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
