/* Generated By:JJTree: Do not edit this line. ASTANDASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTANDASSIGN extends SimpleNode {
  public ASTANDASSIGN(int id) {
    super(id);
  }

  public ASTANDASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aef3a2861ec3dc4947a20700b977be15 (do not edit this line) */
