/* Generated By:JJTree: Do not edit this line. ASTBIT_AND.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTBIT_AND extends SimpleNode {
  public ASTBIT_AND(int id) {
    super(id);
  }

  public ASTBIT_AND(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1326f91bb0ae58e057d508663c5778d (do not edit this line) */
