/* Generated By:JJTree: Do not edit this line. ASTBIT_OR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTBIT_OR extends SimpleNode {
  public ASTBIT_OR(int id) {
    super(id);
  }

  public ASTBIT_OR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6811d73e95af8c1b14fceed79ac15a60 (do not edit this line) */
