/* Generated By:JJTree: Do not edit this line. ASTBANG.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTBANG extends SimpleNode {
  public ASTBANG(int id) {
    super(id);
  }

  public ASTBANG(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=675aee89cf2afbb36582c545df708b0a (do not edit this line) */
