/* Generated By:JJTree: Do not edit this line. ASTBYTE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTBYTE extends SimpleNode {
  public ASTBYTE(int id) {
    super(id);
  }

  public ASTBYTE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a5503316abf5fb2f2ffbab8923ef9bfb (do not edit this line) */
