/* Generated By:JJTree: Do not edit this line. ASTBREAK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTBREAK extends SimpleNode {
  public ASTBREAK(int id) {
    super(id);
  }

  public ASTBREAK(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e600baea1e3a84416f4b175e47cdc34 (do not edit this line) */
