/* Generated By:JJTree: Do not edit this line. ASTBOOLEAN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTBOOLEAN extends SimpleNode {
  public ASTBOOLEAN(int id) {
    super(id);
  }

  public ASTBOOLEAN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a7866c73653a7a2ae6408ac4e623809d (do not edit this line) */
