/* Generated By:JJTree: Do not edit this line. ASTCHAR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTCHAR extends SimpleNode {
  public ASTCHAR(int id) {
    super(id);
  }

  public ASTCHAR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=11b7c10816002db9befe455fbc06d25d (do not edit this line) */
