/* Generated By:JJTree: Do not edit this line. ASTCOMMA.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTCOMMA extends SimpleNode {
  public ASTCOMMA(int id) {
    super(id);
  }

  public ASTCOMMA(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d9786c5bb6bd3115713b2e63d3e2e62 (do not edit this line) */
