/* Generated By:JJTree: Do not edit this line. ASTCHARACTER_LITERAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTCHARACTER_LITERAL extends SimpleNode {
  public ASTCHARACTER_LITERAL(int id) {
    super(id);
  }

  public ASTCHARACTER_LITERAL(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6f4d54d771235e67b7c110e7bfd51c56 (do not edit this line) */
