/* Generated By:JJTree: Do not edit this line. ASTCLASS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTCLASS extends SimpleNode {
  public ASTCLASS(int id) {
    super(id);
  }

  public ASTCLASS(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0eb042bfdac3ee30894ea0377f29f3f (do not edit this line) */
