/* Generated By:JJTree: Do not edit this line. ASTCONTINUE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTCONTINUE extends SimpleNode {
  public ASTCONTINUE(int id) {
    super(id);
  }

  public ASTCONTINUE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51238341660a66230b8c6f51081b6feb (do not edit this line) */
