/* Generated By:JJTree: Do not edit this line. ASTDECR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTDECR extends SimpleNode {
  public ASTDECR(int id) {
    super(id);
  }

  public ASTDECR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bff8deaaac0a6ace36d40ffc70b3add9 (do not edit this line) */
