/* Generated By:JJTree: Do not edit this line. ASTDO.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTDO extends SimpleNode {
  public ASTDO(int id) {
    super(id);
  }

  public ASTDO(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cdcef1a2ec2bf9a2e2d7041ddb6c6b9f (do not edit this line) */
