/* Generated By:JJTree: Do not edit this line. ASTELIF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTELIF extends SimpleNode {
  public ASTELIF(int id) {
    super(id);
  }

  public ASTELIF(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d013b97496f6a6556a16d384ca7860c (do not edit this line) */
