/* Generated By:JJTree: Do not edit this line. ASTELSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTELSE extends SimpleNode {
  public ASTELSE(int id) {
    super(id);
  }

  public ASTELSE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d7e2b4823138e40428c3ac4855fbf76 (do not edit this line) */
