/* Generated By:JJTree: Do not edit this line. ASTEQ.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTEQ extends SimpleNode {
  public ASTEQ(int id) {
    super(id);
  }

  public ASTEQ(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3621cebf4c585df5365c0ad33130a624 (do not edit this line) */
