/* Generated By:JJTree: Do not edit this line. ASTENTER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTENTER extends SimpleNode {
  public ASTENTER(int id) {
    super(id);
  }

  public ASTENTER(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f9c03f681a6e92bf9b5b15bf1b00b2c1 (do not edit this line) */
