/* Generated By:JJTree: Do not edit this line. ASTFALSE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTFALSE extends SimpleNode {
  public ASTFALSE(int id) {
    super(id);
  }

  public ASTFALSE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f20e4058aae81cd0965707e42b753b9d (do not edit this line) */
