/* Generated By:JJTree: Do not edit this line. ASTFLOAT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTFLOAT extends SimpleNode {
  public ASTFLOAT(int id) {
    super(id);
  }

  public ASTFLOAT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f63e10ad45297f4628c87b905bf99abd (do not edit this line) */
