/* Generated By:JJTree: Do not edit this line. ASTFOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTFOR extends SimpleNode {
  public ASTFOR(int id) {
    super(id);
  }

  public ASTFOR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b510a07a1f9224ef80444852a5c1b9d (do not edit this line) */
