/* Generated By:JJTree: Do not edit this line. ASTFLOATING_POINT_LITERAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTFLOATING_POINT_LITERAL extends SimpleNode {
  public ASTFLOATING_POINT_LITERAL(int id) {
    super(id);
  }

  public ASTFLOATING_POINT_LITERAL(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28cdbb56401443a118432fbbe3dfc438 (do not edit this line) */
