/* Generated By:JJTree: Do not edit this line. ASTGE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTGE extends SimpleNode {
  public ASTGE(int id) {
    super(id);
  }

  public ASTGE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1469157e3067e2243aa457bf614e3871 (do not edit this line) */
