/* Generated By:JJTree: Do not edit this line. ASTGT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTGT extends SimpleNode {
  public ASTGT(int id) {
    super(id);
  }

  public ASTGT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05c95b2a496366e9168a076d745ff88e (do not edit this line) */
