/* Generated By:JJTree: Do not edit this line. ASTHOOK.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTHOOK extends SimpleNode {
  public ASTHOOK(int id) {
    super(id);
  }

  public ASTHOOK(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96270e67a08b9aeb5a20579e715162a1 (do not edit this line) */
