/* Generated By:JJTree: Do not edit this line. ASTIDENTIFIER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTIDENTIFIER extends SimpleNode {
  public ASTIDENTIFIER(int id) {
    super(id);
  }

  public ASTIDENTIFIER(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20b352bb2f21a5d9cc4f6d93cf66b052 (do not edit this line) */
