/* Generated By:JJTree: Do not edit this line. ASTIMPORT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTIMPORT extends SimpleNode {
  public ASTIMPORT(int id) {
    super(id);
  }

  public ASTIMPORT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a212c5b3ed6489ec70bacc6411cbd796 (do not edit this line) */
