/* Generated By:JJTree: Do not edit this line. ASTINT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTINT extends SimpleNode {
  public ASTINT(int id) {
    super(id);
  }

  public ASTINT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=effdd8ed2716156696849dc27504ce06 (do not edit this line) */
