/* Generated By:JJTree: Do not edit this line. ASTIMPLEMENT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTIMPLEMENT extends SimpleNode {
  public ASTIMPLEMENT(int id) {
    super(id);
  }

  public ASTIMPLEMENT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5f7dd9dea466e67edddde0f73a66318 (do not edit this line) */
