/* Generated By:JJTree: Do not edit this line. ASTINCR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTINCR extends SimpleNode {
  public ASTINCR(int id) {
    super(id);
  }

  public ASTINCR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bcc7c33f470b70fc4c17493e98dd9349 (do not edit this line) */
