/* Generated By:JJTree: Do not edit this line. ASTINTEGER_LITERAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTINTEGER_LITERAL extends SimpleNode {
  public ASTINTEGER_LITERAL(int id) {
    super(id);
  }

  public ASTINTEGER_LITERAL(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=24f3c38e6d2ee3f06c50552e44e4b6a7 (do not edit this line) */
