/* Generated By:JJTree: Do not edit this line. ASTLE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLE extends SimpleNode {
  public ASTLE(int id) {
    super(id);
  }

  public ASTLE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51c7d49c12df193989d08ddf428b5294 (do not edit this line) */
