/* Generated By:JJTree: Do not edit this line. ASTLBRACE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLBRACE extends SimpleNode {
  public ASTLBRACE(int id) {
    super(id);
  }

  public ASTLBRACE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a90fe9a176916cad622b8f5e6db34895 (do not edit this line) */
