/* Generated By:JJTree: Do not edit this line. ASTLSHIFTASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLSHIFTASSIGN extends SimpleNode {
  public ASTLSHIFTASSIGN(int id) {
    super(id);
  }

  public ASTLSHIFTASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff6840d0d058ef1bf365565abdc389c2 (do not edit this line) */
