/* Generated By:JJTree: Do not edit this line. ASTLSHIFT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLSHIFT extends SimpleNode {
  public ASTLSHIFT(int id) {
    super(id);
  }

  public ASTLSHIFT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=865a4f52dae1be5ff9afcd95bd180bd3 (do not edit this line) */
