/* Generated By:JJTree: Do not edit this line. ASTLONG.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLONG extends SimpleNode {
  public ASTLONG(int id) {
    super(id);
  }

  public ASTLONG(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b4d870be657f5c859fd707a2cf617a4 (do not edit this line) */
