/* Generated By:JJTree: Do not edit this line. ASTLT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLT extends SimpleNode {
  public ASTLT(int id) {
    super(id);
  }

  public ASTLT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f79345b890e9223408463c37c906587 (do not edit this line) */
