/* Generated By:JJTree: Do not edit this line. ASTLBRACKET.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTLBRACKET extends SimpleNode {
  public ASTLBRACKET(int id) {
    super(id);
  }

  public ASTLBRACKET(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60d69b6906a06718c9f6c5fb03daa03e (do not edit this line) */
