/* Generated By:JJTree: Do not edit this line. ASTMINUS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTMINUS extends SimpleNode {
  public ASTMINUS(int id) {
    super(id);
  }

  public ASTMINUS(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=50bb369b646c39170b38b62c0ea3a8a6 (do not edit this line) */
