/* Generated By:JJTree: Do not edit this line. ASTMINUSASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTMINUSASSIGN extends SimpleNode {
  public ASTMINUSASSIGN(int id) {
    super(id);
  }

  public ASTMINUSASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e1d38f15e859546b648653fd4fed8b6b (do not edit this line) */
