/* Generated By:JJTree: Do not edit this line. ASTNEW.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTNEW extends SimpleNode {
  public ASTNEW(int id) {
    super(id);
  }

  public ASTNEW(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14e74888a7fb4086a572dd60d33dd9c1 (do not edit this line) */
