/* Generated By:JJTree: Do not edit this line. ASTNE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTNE extends SimpleNode {
  public ASTNE(int id) {
    super(id);
  }

  public ASTNE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a504d6f156ee5697831ddb7ac78a92d9 (do not edit this line) */
