/* Generated By:JJTree: Do not edit this line. ASTORASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTORASSIGN extends SimpleNode {
  public ASTORASSIGN(int id) {
    super(id);
  }

  public ASTORASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=77974e3bd4ec5c4cbc12a316520f36f0 (do not edit this line) */
