/* Generated By:JJTree: Do not edit this line. ASTPLUS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTPLUS extends SimpleNode {
  public ASTPLUS(int id) {
    super(id);
  }

  public ASTPLUS(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f81ce8fa622084b02aeadf172598f3e (do not edit this line) */
