/* Generated By:JJTree: Do not edit this line. ASTPLUSASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTPLUSASSIGN extends SimpleNode {
  public ASTPLUSASSIGN(int id) {
    super(id);
  }

  public ASTPLUSASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ed23475bd3dc925a8bb5746b0379cc8 (do not edit this line) */
