/* Generated By:JJTree: Do not edit this line. ASTPACKAGE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTPACKAGE extends SimpleNode {
  public ASTPACKAGE(int id) {
    super(id);
  }

  public ASTPACKAGE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d305beaa73955f13907583c5b90d8ed7 (do not edit this line) */
