/* Generated By:JJTree: Do not edit this line. ASTPUBLIC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTPUBLIC extends SimpleNode {
  public ASTPUBLIC(int id) {
    super(id);
  }

  public ASTPUBLIC(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=690cb2fc1b159a7a837a53f2396de75d (do not edit this line) */
