/* Generated By:JJTree: Do not edit this line. ASTPRIVATE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTPRIVATE extends SimpleNode {
  public ASTPRIVATE(int id) {
    super(id);
  }

  public ASTPRIVATE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1800c293e75c26fb968a356d2d8f3590 (do not edit this line) */
