/* Generated By:JJTree: Do not edit this line. ASTRPAREN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRPAREN extends SimpleNode {
  public ASTRPAREN(int id) {
    super(id);
  }

  public ASTRPAREN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c510630626c15ab15d23994b3e24a6a (do not edit this line) */
