/* Generated By:JJTree: Do not edit this line. ASTREMASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTREMASSIGN extends SimpleNode {
  public ASTREMASSIGN(int id) {
    super(id);
  }

  public ASTREMASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d70d45c3aa3f562f61d46d4af3567d5 (do not edit this line) */
