/* Generated By:JJTree: Do not edit this line. ASTREM.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTREM extends SimpleNode {
  public ASTREM(int id) {
    super(id);
  }

  public ASTREM(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a83286a5dc5414da71418bdb85c6c620 (do not edit this line) */
