/* Generated By:JJTree: Do not edit this line. ASTRBRACKET.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRBRACKET extends SimpleNode {
  public ASTRBRACKET(int id) {
    super(id);
  }

  public ASTRBRACKET(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db5d0b028958a56f1b7c4efea8ccf54c (do not edit this line) */
