/* Generated By:JJTree: Do not edit this line. ASTRSIGNEDSHIFTASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRSIGNEDSHIFTASSIGN extends SimpleNode {
  public ASTRSIGNEDSHIFTASSIGN(int id) {
    super(id);
  }

  public ASTRSIGNEDSHIFTASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64776d47146b0a98c2aa8a04b9acace6 (do not edit this line) */
