/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFTASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRUNSIGNEDSHIFTASSIGN extends SimpleNode {
  public ASTRUNSIGNEDSHIFTASSIGN(int id) {
    super(id);
  }

  public ASTRUNSIGNEDSHIFTASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0abdd6a2bb739e750df42e17ec6350bd (do not edit this line) */
