/* Generated By:JJTree: Do not edit this line. ASTRSIGNEDSHIFT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRSIGNEDSHIFT extends SimpleNode {
  public ASTRSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRSIGNEDSHIFT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e98c0aa388a24cd00e130affc92e1c5b (do not edit this line) */
