/* Generated By:JJTree: Do not edit this line. ASTRETURN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRETURN extends SimpleNode {
  public ASTRETURN(int id) {
    super(id);
  }

  public ASTRETURN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=72b9937e537e9622ec808cef557744ef (do not edit this line) */
