/* Generated By:JJTree: Do not edit this line. ASTRBRACE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRBRACE extends SimpleNode {
  public ASTRBRACE(int id) {
    super(id);
  }

  public ASTRBRACE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64286b4d47a6c8f68db4eb3de5a14eee (do not edit this line) */
