/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTRUNSIGNEDSHIFT extends SimpleNode {
  public ASTRUNSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRUNSIGNEDSHIFT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19c46198f6920dd4d5424cb50825992a (do not edit this line) */
