/* Generated By:JJTree: Do not edit this line. ASTSTATIC.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSTATIC extends SimpleNode {
  public ASTSTATIC(int id) {
    super(id);
  }

  public ASTSTATIC(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=079a4654a89f760dba64440c346ad64c (do not edit this line) */
