/* Generated By:JJTree: Do not edit this line. ASTSTAR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSTAR extends SimpleNode {
  public ASTSTAR(int id) {
    super(id);
  }

  public ASTSTAR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e7d92c76037dce524f1fafda8f95b62 (do not edit this line) */
