/* Generated By:JJTree: Do not edit this line. ASTSLASH.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSLASH extends SimpleNode {
  public ASTSLASH(int id) {
    super(id);
  }

  public ASTSLASH(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c9d086afcd394d166ef755881a81615 (do not edit this line) */
