/* Generated By:JJTree: Do not edit this line. ASTSTARASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSTARASSIGN extends SimpleNode {
  public ASTSTARASSIGN(int id) {
    super(id);
  }

  public ASTSTARASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42e917e5cf39825ca50c47d31f0d7ba4 (do not edit this line) */
