/* Generated By:JJTree: Do not edit this line. ASTSTRING_LITERAL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSTRING_LITERAL extends SimpleNode {
  public ASTSTRING_LITERAL(int id) {
    super(id);
  }

  public ASTSTRING_LITERAL(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d8a3c6b603b484841f28221907468238 (do not edit this line) */
