/* Generated By:JJTree: Do not edit this line. ASTSC_OR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSC_OR extends SimpleNode {
  public ASTSC_OR(int id) {
    super(id);
  }

  public ASTSC_OR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=677e821ceb1fd2618b80e34b1e4e970a (do not edit this line) */
