/* Generated By:JJTree: Do not edit this line. ASTSLASHASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSLASHASSIGN extends SimpleNode {
  public ASTSLASHASSIGN(int id) {
    super(id);
  }

  public ASTSLASHASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=971d6e278c18a0e48dd712b4ad027f11 (do not edit this line) */
