/* Generated By:JJTree: Do not edit this line. ASTSC_AND.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSC_AND extends SimpleNode {
  public ASTSC_AND(int id) {
    super(id);
  }

  public ASTSC_AND(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96277fd7f8b3577fbe38f2a3c4bed35d (do not edit this line) */
