/* Generated By:JJTree: Do not edit this line. ASTSHORT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSHORT extends SimpleNode {
  public ASTSHORT(int id) {
    super(id);
  }

  public ASTSHORT(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c870f82c29d8eed3f8d3807b83e1260 (do not edit this line) */
