/* Generated By:JJTree: Do not edit this line. ASTSEMICOLON.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTSEMICOLON extends SimpleNode {
  public ASTSEMICOLON(int id) {
    super(id);
  }

  public ASTSEMICOLON(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64a3883038fc567f47eb146cee8e3a2e (do not edit this line) */
