/* Generated By:JJTree: Do not edit this line. ASTTILDE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTTILDE extends SimpleNode {
  public ASTTILDE(int id) {
    super(id);
  }

  public ASTTILDE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=995358274f7b853a3d576cfa6909355a (do not edit this line) */
