/* Generated By:JJTree: Do not edit this line. ASTVOID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTVOID extends SimpleNode {
  public ASTVOID(int id) {
    super(id);
  }

  public ASTVOID(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4e873485552538fe0394f3eb2558712 (do not edit this line) */
