/* Generated By:JJTree: Do not edit this line. ASTWHILE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTWHILE extends SimpleNode {
  public ASTWHILE(int id) {
    super(id);
  }

  public ASTWHILE(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60b0657471494eb34107b71e3e9a32da (do not edit this line) */
