/* Generated By:JJTree: Do not edit this line. ASTXOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTXOR extends SimpleNode {
  public ASTXOR(int id) {
    super(id);
  }

  public ASTXOR(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a35380ad037017179c30dc31c3f69f27 (do not edit this line) */
