/* Generated By:JJTree: Do not edit this line. ASTXORASSIGN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package sjtu.LexicalAnalyse;

public
class ASTXORASSIGN extends SimpleNode {
  public ASTXORASSIGN(int id) {
    super(id);
  }

  public ASTXORASSIGN(NassauToken p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea84dc0b43b1b903645852117e1752cd (do not edit this line) */
