/* Generated By:JavaCC: Do not edit this line. NassauTokenTreeConstants.java Version 5.0 */

package sjtu.LexicalAnalyse;

public interface NassauTokenTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTBOOLEAN = 2;
  public int JJTBREAK = 3;
  public int JJTBYTE = 4;
  public int JJTCHAR = 5;
  public int JJTCLASS = 6;
  public int JJTCONST = 7;
  public int JJTCONTINUE = 8;
  public int JJTDO = 9;
  public int JJTDOUBLE = 10;
  public int JJTELSE = 11;
  public int JJTELIF = 12;
  public int JJTFALSE = 13;
  public int JJTFLOAT = 14;
  public int JJTFOR = 15;
  public int JJTIF = 16;
  public int JJTIMPLEMENT = 17;
  public int JJTIMPORT = 18;
  public int JJTINT = 19;
  public int JJTLONG = 20;
  public int JJTNEW = 21;
  public int JJTNULL = 22;
  public int JJTPACKAGE = 23;
  public int JJTPRIVATE = 24;
  public int JJTPUBLIC = 25;
  public int JJTRETURN = 26;
  public int JJTSHORT = 27;
  public int JJTSTATIC = 28;
  public int JJTTHIS = 29;
  public int JJTTRUE = 30;
  public int JJTWHILE = 31;
  public int JJTINTEGER_LITERAL = 32;
  public int JJTFLOATING_POINT_LITERAL = 33;
  public int JJTCHARACTER_LITERAL = 34;
  public int JJTSTRING_LITERAL = 35;
  public int JJTIDENTIFIER = 36;
  public int JJTLPAREN = 37;
  public int JJTRPAREN = 38;
  public int JJTLBRACE = 39;
  public int JJTRBRACE = 40;
  public int JJTLBRACKET = 41;
  public int JJTRBRACKET = 42;
  public int JJTSEMICOLON = 43;
  public int JJTCOMMA = 44;
  public int JJTDOT = 45;
  public int JJTASSIGN = 46;
  public int JJTGT = 47;
  public int JJTLT = 48;
  public int JJTBANG = 49;
  public int JJTTILDE = 50;
  public int JJTHOOK = 51;
  public int JJTCOLON = 52;
  public int JJTEQ = 53;
  public int JJTLE = 54;
  public int JJTGE = 55;
  public int JJTNE = 56;
  public int JJTSC_OR = 57;
  public int JJTSC_AND = 58;
  public int JJTINCR = 59;
  public int JJTDECR = 60;
  public int JJTPLUS = 61;
  public int JJTMINUS = 62;
  public int JJTSTAR = 63;
  public int JJTSLASH = 64;
  public int JJTBIT_AND = 65;
  public int JJTBIT_OR = 66;
  public int JJTXOR = 67;
  public int JJTREM = 68;
  public int JJTLSHIFT = 69;
  public int JJTRSIGNEDSHIFT = 70;
  public int JJTRUNSIGNEDSHIFT = 71;
  public int JJTPLUSASSIGN = 72;
  public int JJTMINUSASSIGN = 73;
  public int JJTSTARASSIGN = 74;
  public int JJTSLASHASSIGN = 75;
  public int JJTANDASSIGN = 76;
  public int JJTORASSIGN = 77;
  public int JJTXORASSIGN = 78;
  public int JJTREMASSIGN = 79;
  public int JJTLSHIFTASSIGN = 80;
  public int JJTRSIGNEDSHIFTASSIGN = 81;
  public int JJTRUNSIGNEDSHIFTASSIGN = 82;
  public int JJTENTER = 83;
  public int JJTTAB = 84;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "BOOLEAN",
    "BREAK",
    "BYTE",
    "CHAR",
    "CLASS",
    "CONST",
    "CONTINUE",
    "DO",
    "DOUBLE",
    "ELSE",
    "ELIF",
    "FALSE",
    "FLOAT",
    "FOR",
    "IF",
    "IMPLEMENT",
    "IMPORT",
    "INT",
    "LONG",
    "NEW",
    "NULL",
    "PACKAGE",
    "PRIVATE",
    "PUBLIC",
    "RETURN",
    "SHORT",
    "STATIC",
    "THIS",
    "TRUE",
    "WHILE",
    "INTEGER_LITERAL",
    "FLOATING_POINT_LITERAL",
    "CHARACTER_LITERAL",
    "STRING_LITERAL",
    "IDENTIFIER",
    "LPAREN",
    "RPAREN",
    "LBRACE",
    "RBRACE",
    "LBRACKET",
    "RBRACKET",
    "SEMICOLON",
    "COMMA",
    "DOT",
    "ASSIGN",
    "GT",
    "LT",
    "BANG",
    "TILDE",
    "HOOK",
    "COLON",
    "EQ",
    "LE",
    "GE",
    "NE",
    "SC_OR",
    "SC_AND",
    "INCR",
    "DECR",
    "PLUS",
    "MINUS",
    "STAR",
    "SLASH",
    "BIT_AND",
    "BIT_OR",
    "XOR",
    "REM",
    "LSHIFT",
    "RSIGNEDSHIFT",
    "RUNSIGNEDSHIFT",
    "PLUSASSIGN",
    "MINUSASSIGN",
    "STARASSIGN",
    "SLASHASSIGN",
    "ANDASSIGN",
    "ORASSIGN",
    "XORASSIGN",
    "REMASSIGN",
    "LSHIFTASSIGN",
    "RSIGNEDSHIFTASSIGN",
    "RUNSIGNEDSHIFTASSIGN",
    "ENTER",
    "TAB",
  };
}
/* JavaCC - OriginalChecksum=a4b764402bf2ee4268603341129bd321 (do not edit this line) */
